### ISSUE TITLE
[3.1] If you start search from Specimen Collections page, the collections criteria do not transfer over to /collections/search/index.php

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1324]
Start here: https://cch2.org/portal/collections/index.php

Then click 'Search'. The button will take you to /collections/search/index.php, but NO collections are included in the selection criteria

While most people should be using the new search form, people still have access to the old form, so this should remain back compatible.

**Comment by GregoryPost** [comment]
Minor note: It does work if you select exactly 1 collection...

**Comment by Atticus29** [comment]
@themerekat I think the problem is actually slightly different in this case: collections/index.php really just _shouldn't be part of the logic flow for search/index.php_ . If they're using harvestparams.php, that workflow makes sense because there's no other way to designate collections in that case. By contrast, because search/index.php has the collection accordion included, there should never be a need to end up on collections/index.php in that case.

I think at least part of the problem is that users on CCH2 can currently end up back in collections/index.php from the breadcrumbs of the results page (collections/list.php).

I propose that if `$SHOULD_USE_HARVESTPARAMS = false;` in a portal's symbini.php, that breadcrumb element should be absent (if they arrived at list.php from the search/index.php page).

Are you ok if I implement that instead?

Also, I noticed another related bug, which is that clicking search on the collections/index.php page takes a user to selection/index.php instead of to harvestparams.php when `$SHOULD_USE_HARVESTPARAMS = false;`. I plan on correcting that issue, which is to say I plan on ensuring that collections/index.php always exclusively ends up in harvestparam.php's workflow and never search/index.php's workflow. 

Sound reasonable?

**Comment by Atticus29** [comment]
<img width="1552" alt="Screen Shot 2024-05-20 at 10 45 30 AM" src="https://github.com/BioKIC/Symbiota/assets/2775448/6df6f747-ce11-4030-8f45-a6ae96bf7fb4">

**Comment by themerekat** [comment]
@Atticus29 agreed! Thank you for thinking through this.
