### ISSUE TITLE
Taiwan listed as "Taiwan, Province of China"

### ISSUE THREAD

**Issue by zygoballus** [Symbiota/Symbiota#1381]
In the occurrence editing interface (at least at ecdysis.org), if you try to enter "Taiwan" as the country, it suggests "Taiwan, Province of China". I probably don't need to explain why this is problematic, but just in case... According to Wikipedia, "'Taiwan, China', 'Taiwan, Province of China', and 'Taipei, China' are controversial political terms that claim Taiwan and its associated territories as a province or territory of China." This wording is set in `config/schema/1.0/db_schema-1.0.sql` and was inherited from the original [Symbiota code](https://github.com/search?q=repo%3ASymbiota%2FSymbiota-deprecated%20Taiwan&type=code). We should change it to just "Taiwan", as there is no need for SCAN to take such a political position on the status of Taiwan.'

To fix it at ecdysis.org, someone will probably need to edit the database directly since it's already set.

**Comment by themerekat** [comment]
@zygoballus , see note about future work on the geographic thesaurus versus the geographic lookup table in the issue about South Sudan. In the future, country names will come from GADM.
In the meantime, I've changed the value in Ecdysis. We do not administrate SCAN, so that will have to be done by them.

**Comment by themerekat** [comment]
Part of a broader issue now catalogued here: https://github.com/BioKIC/Symbiota/issues/1424
