### ISSUE TITLE
South Sudan is not included in the geographic thesaurus

### ISSUE THREAD

**Issue by zygoballus** [Symbiota/Symbiota#1383]
South Sudan (which became an independent country in 2011) is not included in the default geographic thesaurus (`config/schema/1.0/db_schema-1.0.sql`). Existing installations will need to add it to their database manually unless some kind of updating script is written.

**Comment by themerekat** [comment]
@zygoballus , the default lookup table you find in the schema is going to be replaced by the new geographic thesaurus, which hooks into GADM via a geographic names harvester. Since GADM includes South Sudan, this will be easily incorporated into future Symbiota portals.

However, as you mention, South Sudan will have to be added to existing Symbiota portals, likely during the update process to Symbiota 3.1

**Comment by themerekat** [comment]
Part of a broader issue now catalogued here: https://github.com/BioKIC/Symbiota/issues/1424
