### ISSUE TITLE
[3.1] Maps not opening correctly from within taxon pages

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/Symbiota#1629]
Bryophyte Portal user reports not being able to open maps via the "Open Interactive Maps" link on a taxon profile.

> While viewing Sphagnum mendocinum species page, clicking on Open Interactive Maps link - we have two different experiences on two computers: On one, it does nothing (we waited a while, it shouldn't be a long loading time). 

I am not able to reproduce this issue (it opens quickly for me using Brave and Chrome) but am inquiring about what browser(s) are being used.

I am, however, able to reproduce this issue in both Brave and Chrome: 
> When she right-clicks on the link, and opens in new tab, it opens the same species page, not a map. Sphagnum capillifolium species page, or any other Sphagnum accessed from a dynamic species list - maps don't open. On my laptop, I get this window:

<img width="796" alt="image (18)" src="https://github.com/user-attachments/assets/8afe067b-d260-4921-9700-ae397a2c9d6d">

Relates to [osTicket #0005178](https://help.symbiota.org/scp/tickets.php?id=4228).

**Comment by GregoryPost** [comment]
Additional Info from Help ticket:

The map problem: it happens when you build a dynamic list from a point on the map, then click on a species on that list, and try to view a map from the species profile that opens from the dynamic checklist.

I was able to confirm the issue on chrome using the process above
