### ISSUE TITLE
[audio player] Add file types that can be selected when you go to upload an audio file

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1674]
From Aidan H: "One though would be to alter the file selection box when uploading. Right now, it only allows images and mp3s to be uploaded, unless you manually switch to "All Files" (add audio/wav and audio/ogg to the accept attribute?)."

**Comment by MuchQuak** [comment]
This is just handled in the Symbini configuration which I have limited for testing purposes. I think it would be helpful to display this at the file upload point so their is no confusion.

![Image](https://github.com/user-attachments/assets/a452ee63-a34c-40fe-b3aa-fabcf86baf62)

Audio support is kinda messy because some browsers support a bunch of different ones but their aren't many that overlap. I think mp3s and wav make sense. I will have to check about ogg because safari does support it but only for new verisons.

**Comment by themerekat** [comment]
That's great to know, thanks!
