### ISSUE TITLE
Full Text upload "cultivated"

### ISSUE THREAD

**Issue by STHerbariumLSU** [Symbiota/Symbiota#1969]
The cultivation status didn't upload in the full text upload in SERNEC.  Data read "yes" for these records.

**Comment by themerekat** [comment]
@STHerbariumLSU , I just checked myself in our documentation, and I think this field requires 0 or 1 instead of "yes" or "no". This might be a change from previously, but I'm not sure.
![image](https://github.com/user-attachments/assets/3296feba-c75b-47dd-8386-ed79c8006e6c)
https://biokic.github.io/symbiota-docs/coll_manager/upload/fields/
