### ISSUE TITLE
Saving other catalog numbers (additional identifier values) not working in Ecdysis

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#216]

**Comment by mandrewj** [comment]
Closing this - I updated ecdysis's base code.  

This was an issue in the updateIdentifiers function in https://github.com/BioKIC/Symbiota/blob/master/classes/OccurrenceEditorManager.php - omoccuridentifiers.identifierName can not be NULL but the original code was forcing NULL instead of an empty string.  

All of this was fixed in https://github.com/BioKIC/Symbiota/commit/d381ceacc6aa4eba4b380829cd236b3d532b69f6

Thanks for documenting it!
