### ISSUE TITLE
[Feature Request]: Standard field for cultivars

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#528]
### Symbiota Portal Name

Any

### Is your feature/tool request related to a problem? Please describe.

Too map to cultivarEpithet DwC field: https://dwc.tdwg.org/terms/#dwc:cultivarEpithet

**Comment by themerekat** [comment]
From Dixie Damrel: "I was wondering if there are plans to make a Cultivar category box after the Scientific name's author? This would be so useful for documented specimens of Botanical Gardens. For the living collection of the South Carolina Botanical Garden, I have the cultivar name typed in (in parentheses after the specific epithet) -- but this really isn't proper. The cultivar name shouldn't really be before the author and it shouldn't be italicized, but that is the way it is turning out. When there is a better way to do this, I would love to correct it properly."

**Comment by Atticus29** [comment]
PR has been issued as a draft [here](https://github.com/BioKIC/Symbiota/pull/1232). Awaiting 3.1 release before merge into Development branch. Already live in USDA branch.

**Comment by Atticus29** [comment]
# Issues that have already been resolved

- Columns for cultivarEpithet and tradeName have been added to the taxa, uploadspectemp, and uploadtaxa tables.
- Taxa with cultivarEpithet and tradeName already searchable in taxa/taxonomy/taxonomydisplay.php
- Taxa with cultivarEpithet and tradeName already editable in taxa/taxonomy/taxoneditor.php. Already fool-proof against end user entering single quotes in cutlvarEpithet or lowercase in tradeName.
- End users can already edit taxa to contain only one or both of cultivarEpithet and tradeName if they select "Cultivar" from rankName.
- End users can already create taxa with one or both cultivarEpithet and tradeName if they select "Cultivar" from rankName. If they do so, the taxon Name field disappears, thereby making the attempted auto-parsing impossible for taxa of this rank. IS THIS AN OK SOLUTION?
- Aesthetics fixes to exclude author from being italicized in TODO.

# Things in need of doing

## Proposed ignore

- Aesthetics fixes to exclude author from being italicized in occurrences where sciname is present but a tidInterpreted is missing to assist with the parsing.
- Depending on the answer to the question below about tidInterpreted, continue to refine and implement the "backup" sciName parser that gets used if tidInterpreted is missing from the $occArr.

## TODO
- Selecting a non-cultivar rankName from taxa/taxonomy/taxoneditor.php when editing a taxon doesn't remove cultivarEpithet
- Harlan's issue with bulk import of taxonomic names with cultivars and/or trade names.

## Done

- Reproduce and characterize the issue Katie is experiencing where cultivar rankName is being added to sciName during full text upload.

# Questions
- occurrenceeditor.php?occid=6021924
    - Why do we allow end users to enter taxa at all that are not already in the taxa table? The warning is nice, but should we allow it at all?
- Should cultivarEpithet and tradeName be fields in the omoccurrences table?
    - If not, how do we deal with parsing sciname (say, for formatting their display name) where tidInterpreted is missing? This can happen both when occurrences are created via batch upload or when they are created manually.
- Sciname display, regardless of whether the styling is composed and rendered client-side or stored in the database. In either case, access to the taxa table seems to be required at some step in order to figure out what needs to be styled and where. How do we handle the cases where a tidInterpreted is missing, and we only have sciname to rely on?

# Formatting

taxonRanks = [Agamospecies, sub-lesus, prole, apomict, nothogrex, sp., subsp., var., subspecies, varietas, forma, f., species, nothogenus, nothospecies, nothosubspecies]... what about genus? Any others missing?

<i>genus</i> + <i>specificEpithet</i> + taxonRank (if in taxonRanks list, include. Otherwise, don't?),  + infraspecificEpithet + scientificNameAuthorship + cultivarEpithet (make sure has single quotes) + tradeName (make sure all capitalized).

Per Harlan's suggestion, if cultivarEpithet or tradeName is present, it is convention _not_ to display scientificNameAuthorship.

**Comment by themerekat** [comment]
> * End users can already create taxa with one or both cultivarEpithet and tradeName if they select "Cultivar" from rankName. If they do so, the taxon Name field disappears, thereby making the attempted auto-parsing impossible for taxa of this rank. IS THIS AN OK SOLUTION?

I am also curious whether @egbot thinks this is an appropriate solution. It prevents us having to rework the parser to be able to auto-parse cultivars and trade names, which I feel like would be a big lift.

> * Aesthetics fixes to exclude author from being italicized in occurrences where sciname is present but a tidInterpreted is missing to assist with the parsing.

I don't think we have to fix this. It's actually kind of helpful to have the formatting "incorrect" when the name isn't linked to a tidInterpreted because then you know that it's not in the thesaurus.

> # Questions
> * occurrenceeditor.php?occid=6021924
>   * Why do we allow end users to enter taxa at all that are not already in the taxa table? The warning is nice, but should we allow it at all?

This is actually an important feature of Symbiota. Other databases don't allow you to enter scientific names that aren't matched to their taxonomic thesauri, which ends up (1) slowing down digitization workflows and (2) creating messy thesauri, as people add not-actually-real-but-practical names to the thesaurus.

Many names get added to the thesaurus _from_ the unindexed names in the occurrence records (using the taxonomic cleaning tool). This is the primary way that we populate the taxonomic thesaurus unless someone has a particular taxonomic authority file they want us to pre-load in.

Lastly, we simply wouldn't be able to keep up with the number of requests to add new taxa if names had to be added to the thesaurus before they could be entered.

All of this is not necessarily "best practice" in terms of data or standards, but it reflects the practical compromises we make so that Symbiota is both aligned with data standards and user friendly, even for inexperienced data users.

> * Should cultivarEpithet and tradeName be fields in the omoccurrences table?
>   
>   * If not, how do we deal with parsing sciname (say, for formatting their display name) where tidInterpreted is missing? This can happen both when occurrences are created via batch upload or when they are created manually.

No, Ed is reworking this so that all determinations / scientific names are going to be stored in omoccurdeterminations and nowhere else (if I understand correctly). As mentioned above, you do not need to have correct styling for names that are not indexed to the thesaurus (i.e., have a tidInterpreted). Their lack of styling is a useful indicator of their lack of being indexed.

> * Sciname display, regardless of whether the styling is composed and rendered client-side or stored in the database. In either case, access to the taxa table seems to be required at some step in order to figure out what needs to be styled and where. How do we handle the cases where a tidInterpreted is missing, and we only have sciname to rely on?

See above. We don't have to style things that aren't indexed.

**Comment by themerekat** [comment]
> # Formatting
> taxonRanks = [Agamospecies, sub-lesus, prole, apomict, nothogrex, sp., subsp., var., subspecies, varietas, forma, f., species, nothogenus, nothospecies, nothosubspecies]... what about genus? Any others missing?
> 
> genus + specificEpithet + taxonRank (if in taxonRanks list, include. Otherwise, don't?), + infraspecificEpithet + scientificNameAuthorship + cultivarEpithet (make sure has single quotes) + tradeName (make sure all capitalized).
> 
> Per Harlan's suggestion, if cultivarEpithet or tradeName is present, it is convention _not_ to display scientificNameAuthorship.

Wow, I am not a taxonomist, so I have no clue about most of those taxon ranks. The only ones I'm familiar with are subsp., subspecies, forma, f., var., variety.

I don't think you need to include "sp." as a rank. It will just mean that the name stops at genus.
